### ISSUE TITLE
On windows 10, clang-format.el is not obeying .clang-format but it follows _clang-format file from the project Repository.

### ISSUE THREAD

**Issue by justinjk007** [sonatard/clang-format#1]
So I have this is my `init.el`
```clojure
    (use-package clang-format
      :init
      (global-set-key (kbd "C-c r") 'clang-format-region)
      (global-set-key (kbd "C-c u") 'clang-format-buffer)
      :config
      (setq clang-format-style-option "file")
      )
```
And this in my `.clang-format`
``` YAML
    BasedOnStyle: Google
    Language: Cpp
    Standard: Cpp11
    Cpp11BracedListStyle: true
    IndentWidth: 4
    ColumnLimit: 100
    BreakBeforeBraces: Linux
    AlignAfterOpenBracket: Align
    AlignConsecutiveAssignments: true
    AlignOperands: true
    AllowShortFunctionsOnASingleLine: Empty
    DerivePointerAlignment: false
    PointerAlignment: Left
 ```   
   
 If I make a `_clang-format` in any Repository or project directory, then clang-format obeys that file, but It never follows `.clang-format` file from my home directory , any reason why ?
